### ISSUE TITLE
Out-of-tree compilation error on POT files on Ubuntu

### ISSUE THREAD

**Issue by Mutos** [naev/naev#1362]
Hello all,

I got this error at the end of compilation :

```
Making all in po
  LN    ../../naev
ITSTOOL ../../po/xml.pot
/bin/bash: ./utils/gettext.sh: Aucun fichier ou dossier de ce type
Makefile:1117: recipe for target 'pot' failed
make[1]: *** [pot] Error 127
Makefile:668: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

It fails under Ubuntu 18.04.5 LTS and for now I can't test the same under Windows.

It seems that the translation mechanism is currently not configured for OOT compilation. I already had to do the following to make it take correctly the XML files :

```
cd bin/lin64
ln -s ../../dat ./dat
```
I can't get to find why, being ignorant in **_make_** and translation mechanisms. Could anyone provide an insight about what's happening ? Thanks in advance !

@+
Benoît 'Mutos' Robin

**Comment by bobbens** [comment]
I will look into it, but for out-of-tree builds, chances are you should be using meson (new build system we recently started supported). Instructions should be in the readme.

**Comment by bobbens** [comment]
Should be fixed in master!

**Comment by Mutos** [comment]
Hello bobbens, hello all,


Doesn't seem to work, I use the usual autogen/configure/make workflow and I get the following message : 

```
Making all in po
/usr/bin/xgettext: Erreur lors de l'ouverture de « dat/ai/advertiser.lua » en lecture : Aucun fichier ou dossier de ce type
ERROR: xgettext failed to generate PO template file. Please consult
       error message above if there is any.
Makefile:561: recipe for target 'naev.pot' failed
```

If I symlink dat in bin/lin64 to the original dat, it finds that file, but does the same for a file in src : 

```
Making all in po
/usr/bin/xgettext: Erreur lors de l'ouverture de « src/ai.c » en lecture : Aucun fichier ou dossier de ce type
ERROR: xgettext failed to generate PO template file. Please consult
       error message above if there is any.
Makefile:561: recipe for target 'naev.pot' failed
```
Btw, just noticed messages are a mix of french and english, but they should be fairly direct to understand.

And this time I cannot symlink src, as this would defeat the whole purpose of OOT compilation...

I'll look at that meson thing in the readme, hoping it can be understood without any prior knowledge of make...


@+
Benoît 'Mutos' Robin

**Comment by Mutos** [comment]
Hello bobbens, hello all,


Just tried meson, on paper it looks easy to use, installed it from package by a 'sudo apt-get meson` and used 'meson setup builddir .' as instructed. It didn't work and I got this message : 

```
$ meson setup builddir .
The Meson build system
Version: 0.45.1
Source dir: /mnt/data/dev/NAEV/020-Dev/Repositories/naev
Build dir: /mnt/data/dev/NAEV/020-Dev/Repositories/naev/builddir
Build type: native build

meson.build:69:20: ERROR: Expecting eol got not.
   if 'SuiteSparse' not in get_option('force_fallback_for')
                    ^

A full log can be found at /mnt/data/dev/NAEV/020-Dev/Repositories/naev/builddir/meson-logs/meson-log.txt
```
The so-called full log just contains the same messages, so no further insight. I searched on the net for the error code and message, found nothing.

Could someone have a hint out of the dead-end ? Thanks in advance.


@+
Benoît 'Mutos' Robin

**Comment by Mutos** [comment]
Hello,

Just realised `meson.build:69:20:` is the config file with line and column. Useless but it makes me feel less stupid than 5mn before...

@+
Mutos

**Comment by Mutos** [comment]
Hello all,

I finally got **_meson_** to work with another install : first removing the apt **_meson_**, then installing **_python3-pip_** and running `sudo pip3 install meson`.

meson version is 0.56.0, was previously 0.45.1, and that changed all...

Anyway, there is still an issue, but with a depenancy : 

`
meson.build:157:3: ERROR: Dependency "SDL2_mixer" not found, tried pkgconfig and cmake
`

@+
Mutos

**Comment by Mutos** [comment]
Hi all,

Seems the development environment for sdl2_mixer wasn't installed. `sudo apt-get install libsdl2-mixer-dev` did the trick.

Doc in french, an english version is certainly somewhere out : 
    https://doc.ubuntu-fr.org/sdl

@+
Mutos

**Comment by Mutos** [comment]
Hi all,

OK, still had to install Ninja with `sudo pip3 install ninja` and `meson` finally agreed to setup the builddir and compile, and I could run naev correctly.

Now I have to get it working on Windows for compiling win32 and win64...

@+
Mutos
